language: python
python:
    - "2.6"
    - "2.7"
    - "3.3"
    - "3.4"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi
    - pip install . --use-mirrors
script: cd tests && nosetests

notifications:
    email:
        on_success: never
        on_failure: always
